### PR TITLE
Use fabsf where input is a float32

### PR DESCRIPTION
**Pull request by mehmetoguzderin**
This PR unifies all absolute value usage where input is a float32 to be `fabsf`, replacing `fabs` use at places.

### CODE REVIEW

**Comment by NeilBickford-NV** [comment]
Hi Mehmet! Sorry for the long wait - we just changed the license on GVDB in order to accept pull requests. If you're up for contributing this to GVDB, could you sign-off on your commits by going to your branch, then running

`git rebase HEAD~2 --signoff`

followed by

`git push --force-with-lease`

? This should add a line to each of the commit messages like this:

`Signed-off-by: Contributor Name <email>`

Once that's done, I can accept the pull request. Thanks!

**Comment by mehmetoguzderin** [comment]
@NeilBickford-NV Sure thing, congrats on the new licensing! Did the steps on this branch!

**Comment by NeilBickford-NV** [comment]
Perfect, merged! Thanks for helping out with this!

**Comment by mehmetoguzderin** [comment]
Have a great week, thanks for maintaining GVDB!

**Pull request merged**
